/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.module.extension.studio.model;

import org.mule.module.extension.studio.model.element.AttributeCategory;
import org.mule.module.extension.studio.model.element.BooleanEditor;
import org.mule.module.extension.studio.model.element.Button;
import org.mule.module.extension.studio.model.element.Case;
import org.mule.module.extension.studio.model.element.ChildElement;
import org.mule.module.extension.studio.model.element.ClassNameEditor;
import org.mule.module.extension.studio.model.element.Custom;
import org.mule.module.extension.studio.model.element.DateTimeEditor;
import org.mule.module.extension.studio.model.element.Dummy;
import org.mule.module.extension.studio.model.element.DynamicEditor;
import org.mule.module.extension.studio.model.element.EditorRef;
import org.mule.module.extension.studio.model.element.ElementControllerList;
import org.mule.module.extension.studio.model.element.ElementControllerListNoExpression;
import org.mule.module.extension.studio.model.element.ElementControllerListOfMap;
import org.mule.module.extension.studio.model.element.ElementControllerListOfPojo;
import org.mule.module.extension.studio.model.element.ElementControllerMap;
import org.mule.module.extension.studio.model.element.ElementControllerMapNoExpression;
import org.mule.module.extension.studio.model.element.ElementQuery;
import org.mule.module.extension.studio.model.element.EncodingEditor;
import org.mule.module.extension.studio.model.element.EnumEditor;
import org.mule.module.extension.studio.model.element.FileEditor;
import org.mule.module.extension.studio.model.element.FixedAttribute;
import org.mule.module.extension.studio.model.element.Group;
import org.mule.module.extension.studio.model.element.Horizontal;
import org.mule.module.extension.studio.model.element.IntegerEditor;
import org.mule.module.extension.studio.model.element.LabelElement;
import org.mule.module.extension.studio.model.element.ListEditor;
import org.mule.module.extension.studio.model.element.LongEditor;
import org.mule.module.extension.studio.model.element.Mode;
import org.mule.module.extension.studio.model.element.ModeSwitch;
import org.mule.module.extension.studio.model.element.NameEditor;
import org.mule.module.extension.studio.model.element.NoOperation;
import org.mule.module.extension.studio.model.element.Option;
import org.mule.module.extension.studio.model.element.PasswordEditor;
import org.mule.module.extension.studio.model.element.PathEditor;
import org.mule.module.extension.studio.model.element.RadioBoolean;
import org.mule.module.extension.studio.model.element.Regexp;
import org.mule.module.extension.studio.model.element.RequiredLibraries;
import org.mule.module.extension.studio.model.element.ResourceEditor;
import org.mule.module.extension.studio.model.element.SoapInterceptor;
import org.mule.module.extension.studio.model.element.StringEditor;
import org.mule.module.extension.studio.model.element.StringMap;
import org.mule.module.extension.studio.model.element.SwitchCase;
import org.mule.module.extension.studio.model.element.TextEditor;
import org.mule.module.extension.studio.model.element.TimeEditor;
import org.mule.module.extension.studio.model.element.TypeChooser;
import org.mule.module.extension.studio.model.element.UrlEditor;
import org.mule.module.extension.studio.model.element.UseMetaData;
import org.mule.module.extension.studio.model.element.library.Jar;
import org.mule.module.extension.studio.model.element.library.LibrarySet;
import org.mule.module.extension.studio.model.element.library.NativeLibrary;
import org.mule.module.extension.studio.model.global.CloudConnectorMessageSource;
import org.mule.module.extension.studio.model.global.Global;
import org.mule.module.extension.studio.model.global.GlobalCloudConnector;
import org.mule.module.extension.studio.model.global.GlobalEndpoint;
import org.mule.module.extension.studio.model.global.GlobalFilter;
import org.mule.module.extension.studio.model.global.GlobalTransformer;
import org.mule.module.extension.studio.model.reference.ContainerRef;
import org.mule.module.extension.studio.model.reference.FlowRef;
import org.mule.module.extension.studio.model.reference.GlobalRef;
import org.mule.module.extension.studio.model.reference.ReverseGlobalRef;

public interface IEditorElementVisitor
{

    void visit(CloudConnectorMessageSource cloudConnectorMessageSource);
    void visit(Global global);
    void visit(GlobalCloudConnector globalCloudConnector);
    void visit(GlobalEndpoint globalEndpoint);
    void visit(GlobalFilter globalFilter);
    void visit(GlobalTransformer globalTransformer);
    void visit(AttributeCategory attributeCategory);
    void visit(BooleanEditor booleanEditor);
    void visit(Button button);
    void visit(Case caseEditorElement);
    void visit(ChildElement childElement);
    void visit(ClassNameEditor classNameEditor);
    void visit(Custom custom);
    void visit(Dummy dummy);
    void visit(DateTimeEditor datetime);
    void visit(DynamicEditor dynamicEditor);
    void visit(EditorRef editorRef);
    void visit(ElementControllerList elementControllerList);
    void visit(ElementControllerListNoExpression elementControllerListNoExpression);
    void visit(ElementControllerListOfMap elementControllerListOfMap);
    void visit(ElementControllerListOfPojo elementControllerListOfPojo);
    void visit(ElementControllerMap elementControllerMap);
    void visit(ElementControllerMapNoExpression elementControllerMapNoExpression);
    void visit(ElementQuery elementQuery);
    void visit(EncodingEditor encodingEditor);
    void visit(EnumEditor enumEditor);
    void visit(FileEditor fileEditor);
    void visit(FixedAttribute fixedAttribute);
    void visit(Group group);
    void visit(Horizontal horizontal);
    void visit(IntegerEditor integerEditor);
    void visit(LabelElement labelElement);
    void visit(ListEditor listEditor);
    void visit(LongEditor longEditor);
    void visit(Mode mode);
    void visit(ModeSwitch modeSwitch);
    void visit(NameEditor nameEditor);
    void visit(NativeLibrary nativeLibrary);
    void visit(NoOperation noOperation);
    void visit(Option option);
    void visit(PasswordEditor passwordEditor);
    void visit(PathEditor pathEditor);
    void visit(RadioBoolean radioBoolean);
    void visit(Regexp regexp);
    void visit(RequiredLibraries requiredLibraries);
    void visit(ResourceEditor resource);
    void visit(SoapInterceptor soapInterceptor);
    void visit(StringEditor stringEditor);
    void visit(StringMap stringMap);
    void visit(SwitchCase switchCase);
    void visit(TextEditor textEditor);
    void visit(TimeEditor timeEditor);
    void visit(TypeChooser typeChooser);
    void visit(UrlEditor urlEditor);
    void visit(UseMetaData useMetaData);
    void visit(Jar jar);
    void visit(LibrarySet librarySet);
    void visit(ContainerRef containerRef);
    void visit(FlowRef flowRef);
    void visit(GlobalRef globalRef);
    void visit(ReverseGlobalRef reverseGlobalRef);
    void visit(Alternative alternative);
    void visit(CloudConnector cloudConnector);
    void visit(Component component);
    void visit(Connector connector);
    void visit(Container container);
    void visit(Endpoint endpoint);
    void visit(Filter filter);
    void visit(Flow flow);
    void visit(GraphicalContainer graphicalContainer);
    void visit(Keyword keyword);
    void visit(KeywordSet keywordSet);
    void visit(LocalRef localRef);
    void visit(MultiSource multiSource);
    void visit(Namespace namespace);
    void visit(Nested nested);
    void visit(NestedContainer nestedContainer);
    void visit(Pattern pattern);
    void visit(Radio radio);
    void visit(RequiredSetAlternatives requiredSetAlternatives);
    void visit(Transformer transformer);
    void visit(Wizard wizard);

}
